// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHlFtM3WUuPqImSv0Y5BMjx1-LucXNw7k',
    appId: '1:126947962226:web:f52e62946d68ba945581eb',
    messagingSenderId: '126947962226',
    projectId: 'flutter-firebase-dersler-e18e8',
    authDomain: 'flutter-firebase-dersler-e18e8.firebaseapp.com',
    storageBucket: 'flutter-firebase-dersler-e18e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4skwlL7QvuREb3zfxIsHfVH1UlyT6-Es',
    appId: '1:126947962226:android:e786274edb1463385581eb',
    messagingSenderId: '126947962226',
    projectId: 'flutter-firebase-dersler-e18e8',
    storageBucket: 'flutter-firebase-dersler-e18e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdIdIvTz0wr8EnhDyU1akfrEn20MGOVU8',
    appId: '1:126947962226:ios:10559fedc026489f5581eb',
    messagingSenderId: '126947962226',
    projectId: 'flutter-firebase-dersler-e18e8',
    storageBucket: 'flutter-firebase-dersler-e18e8.firebasestorage.app',
    iosBundleId: 'com.eminalan334.flutterFirebaseDersleri',
  );
}
